services:
  backend:
    build: backend
    container_name: backend-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # configure postgres DB
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rock-paper-scissors-db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=Backend
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD} # the DB password of the user must be in an .env file
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=never # never show health details in actuators
      - API_KEY=${API_KEY} # the API-Key of the Spring Boot API must be in an .env file
      - CORS_ALLOWED_ORIGINS=http://backend-for-frontend:3000

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=Backend
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=rock-paper-scissors-db
    volumes:
      - db-data:/var/lib/postgresql
    expose:
      - 5432

  backend-for-frontend:
    build: backend-for-frontend
    container_name: backend-for-frontend-app
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8080/rock-paper-scissors/games
      - BACKEND_API_KEY=${API_KEY}
      - CORS_ALLOWED_ORIGIN=http://127.0.0.1:80

  frontend:
    build: frontend
    container_name: frontend-app
    depends_on:
      - backend-for-frontend
    ports:
      - "80:80"

volumes:
  db-data:
