services:
  backend:
    build: backend
    container_name: backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # configure postgres DB
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rock-paper-scissors-db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=Backend
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD} # the DB password of the user must be in an .env file
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=never # never show health details in actuators
      - API_KEY=${API_KEY} # the API-Key of the Spring Boot API must be in an .env file
    networks:
      - spring-postgres
  db:
    image: postgres
    container_name: db
    restart: always
    networks:
      - spring-postgres
    environment:
      - POSTGRES_USER=Backend
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=rock-paper-scissors-db
    expose:
      - 5432
networks:
  spring-postgres: